// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sky.Infrastructure;

#nullable disable

namespace Sky.Infrastructure.Migrations
{
    [DbContext(typeof(SkyDBContext))]
    [Migration("20230718004610_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sky.Domain.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Line2")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AccCashId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccDiscountAcquiredId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccInventoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccPurchasesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccPurchasesReturnsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccSalesCostId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccSalesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccSalesTaxonPurchasesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AccSuppliersId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CommercialNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DefaultCostCenterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultInventoryId")
                        .HasColumnType("bigint");

                    b.Property<int?>("InventoryAccountingTypes")
                        .HasColumnType("int");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoURL")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<bool?>("ShowLogo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SiteURL")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("SystemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientId = 1L,
                            Code = "001",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false,
                            Name = "Main Branch"
                        });
                });

            modelBuilder.Entity("Sky.Domain.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryName = "Afghanistan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 2L,
                            CountryName = "Albania",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 3L,
                            CountryName = "Algeria",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 4L,
                            CountryName = "American Samoa",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 5L,
                            CountryName = "Andorra",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 6L,
                            CountryName = "Angola",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 7L,
                            CountryName = "Anguilla",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 8L,
                            CountryName = "Antarctica",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 9L,
                            CountryName = "Antigua and Barbuda",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 10L,
                            CountryName = "Argentina",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 11L,
                            CountryName = "Armenia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 12L,
                            CountryName = "Aruba",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 13L,
                            CountryName = "Australia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 14L,
                            CountryName = "Austria",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 15L,
                            CountryName = "Azerbaijan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 16L,
                            CountryName = "Bahamas",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 17L,
                            CountryName = "Bahrain",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 18L,
                            CountryName = "Bangladesh",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 19L,
                            CountryName = "Barbados",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 20L,
                            CountryName = "Belarus",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 21L,
                            CountryName = "Belgium",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 22L,
                            CountryName = "Belize",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 23L,
                            CountryName = "Benin",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 24L,
                            CountryName = "Bermuda",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 25L,
                            CountryName = "Bhutan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 26L,
                            CountryName = "Bolivia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 27L,
                            CountryName = "Bosnia and Herzegovina",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 28L,
                            CountryName = "Botswana",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 29L,
                            CountryName = "Bouvet Island",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 30L,
                            CountryName = "Brazil",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 31L,
                            CountryName = "British Indian Ocean Territories",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 32L,
                            CountryName = "Brunei Darussalam",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 33L,
                            CountryName = "Bulgaria",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 34L,
                            CountryName = "Burkina Faso",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 35L,
                            CountryName = "Burundi",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 36L,
                            CountryName = "Cambodia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 37L,
                            CountryName = "Cameroon",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 38L,
                            CountryName = "Canada",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 39L,
                            CountryName = "Cape Verde",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 40L,
                            CountryName = "Cayman Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 41L,
                            CountryName = "Central African Republic",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 42L,
                            CountryName = "Chad",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 43L,
                            CountryName = "Chile",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 44L,
                            CountryName = "China",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 45L,
                            CountryName = "Christmas Island",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 46L,
                            CountryName = "Cocos Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 47L,
                            CountryName = "Columbia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 48L,
                            CountryName = "Comoros",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 49L,
                            CountryName = "Congo",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 50L,
                            CountryName = "Cook Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 51L,
                            CountryName = "Costa Rica",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 52L,
                            CountryName = "Cote D'ivoire",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 53L,
                            CountryName = "Croatia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 54L,
                            CountryName = "Cuba",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 55L,
                            CountryName = "Cyprus",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 56L,
                            CountryName = "Czech Republic",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 57L,
                            CountryName = "Djibouti",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 58L,
                            CountryName = "Dominica",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 59L,
                            CountryName = "Dominican Republic",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 60L,
                            CountryName = "East Timor",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 61L,
                            CountryName = "Ecuador",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 62L,
                            CountryName = "Egypt",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 63L,
                            CountryName = "El Salvador",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 64L,
                            CountryName = "Equatorial Guinea",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 65L,
                            CountryName = "Eritrea",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 66L,
                            CountryName = "Estonia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 67L,
                            CountryName = "Ethiopia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 68L,
                            CountryName = "Falkland Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 69L,
                            CountryName = "Faroe Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 70L,
                            CountryName = "Finland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 71L,
                            CountryName = "France",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 72L,
                            CountryName = "France, Metropolitan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 73L,
                            CountryName = "French Guiana",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 74L,
                            CountryName = "French Polynesia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 75L,
                            CountryName = "Fiji",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 76L,
                            CountryName = "French Southern Territories",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 77L,
                            CountryName = "FYROM",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 78L,
                            CountryName = "Gabon",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 79L,
                            CountryName = "Gambia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 80L,
                            CountryName = "Georgia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 81L,
                            CountryName = "Germany",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 82L,
                            CountryName = "Ghana",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 83L,
                            CountryName = "Greece",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 84L,
                            CountryName = "Greenland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 85L,
                            CountryName = "Grenada",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 86L,
                            CountryName = "Guadeloupe",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 87L,
                            CountryName = "Guam",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 88L,
                            CountryName = "Gibraltar",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 89L,
                            CountryName = "Guatemala",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 90L,
                            CountryName = "Guinea",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 91L,
                            CountryName = "Guinea-Bissau",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 92L,
                            CountryName = "Guyana",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 93L,
                            CountryName = "Haiti",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 94L,
                            CountryName = "Heard Island And Mcdonald Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 95L,
                            CountryName = "Honduras",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 96L,
                            CountryName = "Hong Kong",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 97L,
                            CountryName = "Hungary",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 98L,
                            CountryName = "Iceland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 99L,
                            CountryName = "India",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 101L,
                            CountryName = "Indonesia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 102L,
                            CountryName = "Iran",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 103L,
                            CountryName = "Iraq",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 104L,
                            CountryName = "Ireland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 105L,
                            CountryName = "Italy",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 106L,
                            CountryName = "Jamaica",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 107L,
                            CountryName = "Japan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 108L,
                            CountryName = "Jordan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 109L,
                            CountryName = "Kazakhstan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 110L,
                            CountryName = "Kenya",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 111L,
                            CountryName = "Kiribati",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 112L,
                            CountryName = "Korea, Democratic Peoples Republic of",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 113L,
                            CountryName = "Korea, Republic of",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 114L,
                            CountryName = "Kuwait",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 115L,
                            CountryName = "Kyrgyzstan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 116L,
                            CountryName = "Lao Peoples Democratic Republic",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 117L,
                            CountryName = "Latvia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 118L,
                            CountryName = "Lebanon",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 119L,
                            CountryName = "Lesotho",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 120L,
                            CountryName = "Liberia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 121L,
                            CountryName = "Libyan Arab Jamahiriya",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 122L,
                            CountryName = "Liechtenstein",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 123L,
                            CountryName = "Lithuania",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 124L,
                            CountryName = "Luxembourg",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 125L,
                            CountryName = "Macau",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 126L,
                            CountryName = "Madagascar",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 127L,
                            CountryName = "Malawi",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 128L,
                            CountryName = "Malaysia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 129L,
                            CountryName = "Maldives",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 130L,
                            CountryName = "Mali",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 131L,
                            CountryName = "Malta",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 132L,
                            CountryName = "Marshall Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 133L,
                            CountryName = "Martinique",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 134L,
                            CountryName = "Mauritania",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 135L,
                            CountryName = "Mauritius",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 136L,
                            CountryName = "Mayotte",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 137L,
                            CountryName = "Mexico",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 138L,
                            CountryName = "Micronesia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 139L,
                            CountryName = "Moldova",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 140L,
                            CountryName = "Mongolia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 141L,
                            CountryName = "Montserrat",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 142L,
                            CountryName = "Morocco",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 143L,
                            CountryName = "Monaco",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 144L,
                            CountryName = "Myanmar",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 145L,
                            CountryName = "Mozambique",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 146L,
                            CountryName = "Namibia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 147L,
                            CountryName = "Nauru",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 148L,
                            CountryName = "Nepal",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 149L,
                            CountryName = "Netherlands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 150L,
                            CountryName = "Netherlands Antilles",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 151L,
                            CountryName = "New Caledonia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 152L,
                            CountryName = "New Zealand",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 153L,
                            CountryName = "Nicaragua",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 154L,
                            CountryName = "Niger",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 155L,
                            CountryName = "Nigeria",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 156L,
                            CountryName = "Niue",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 157L,
                            CountryName = "Norfolk Island",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 158L,
                            CountryName = "Northern Mariana Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 159L,
                            CountryName = "Norway",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 160L,
                            CountryName = "Oman",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 161L,
                            CountryName = "Pakistan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 162L,
                            CountryName = "palestine",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 163L,
                            CountryName = "Palau",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 164L,
                            CountryName = "Panama",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 165L,
                            CountryName = "Papua New Guinea",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 166L,
                            CountryName = "Paraguay",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 167L,
                            CountryName = "Peru",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 168L,
                            CountryName = "Philippines",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 169L,
                            CountryName = "Pitcairn",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 170L,
                            CountryName = "Poland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 171L,
                            CountryName = "Portugal",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 172L,
                            CountryName = "Puerto Rico",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 173L,
                            CountryName = "Qatar",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 174L,
                            CountryName = "Reunion",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 175L,
                            CountryName = "Romania",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 176L,
                            CountryName = "Russian Federation",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 177L,
                            CountryName = "Rwanda",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 178L,
                            CountryName = "Saint Helena",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 179L,
                            CountryName = "Saint Kitts and Nevis",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 180L,
                            CountryName = "Saint Lucia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 181L,
                            CountryName = "Saint Pierre and Miquelon",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 182L,
                            CountryName = "Saint Vincent and The Grenadines",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 183L,
                            CountryName = "Samoa",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 184L,
                            CountryName = "San Marino",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 185L,
                            CountryName = "Sao Tome and Principe",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 186L,
                            CountryName = "Saudi Arabia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 187L,
                            CountryName = "Senegal",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 188L,
                            CountryName = "Seychelles",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 189L,
                            CountryName = "Sierra Leone",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 191L,
                            CountryName = "Singapore",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 192L,
                            CountryName = "Slovakia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 193L,
                            CountryName = "Slovenia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 194L,
                            CountryName = "Solomon Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 195L,
                            CountryName = "Somalia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 196L,
                            CountryName = "South Africa",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 197L,
                            CountryName = "South Georgia and Sandwich Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 198L,
                            CountryName = "Spain",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 199L,
                            CountryName = "Sri Lanka",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 200L,
                            CountryName = "Sudan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 201L,
                            CountryName = "Suriname",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 202L,
                            CountryName = "Svalbard and JanMayen",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 203L,
                            CountryName = "Swaziland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 204L,
                            CountryName = "Sweden",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 205L,
                            CountryName = "Switzerland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 206L,
                            CountryName = "Syrian Arab Republic",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 207L,
                            CountryName = "Taiwan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 208L,
                            CountryName = "Tajikistan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 209L,
                            CountryName = "Tanzania",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 210L,
                            CountryName = "Thailand",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 211L,
                            CountryName = "Tokelau",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 212L,
                            CountryName = "Tonga",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 213L,
                            CountryName = "Trinidad and Tobago",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 214L,
                            CountryName = "Tunisia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 215L,
                            CountryName = "Togo",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 216L,
                            CountryName = "Turkey",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 217L,
                            CountryName = "Turkmenistan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 218L,
                            CountryName = "Turks and Caicos Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 219L,
                            CountryName = "Tuvalu",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 220L,
                            CountryName = "Uganda",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 221L,
                            CountryName = "Ukraine",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 222L,
                            CountryName = "United Arab Emirates",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 223L,
                            CountryName = "United Kingdom",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 224L,
                            CountryName = "United States",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 225L,
                            CountryName = "Uruguay",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 226L,
                            CountryName = "Uzbekistan",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 227L,
                            CountryName = "Vanuatu",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 228L,
                            CountryName = "Vatican City State",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 229L,
                            CountryName = "Venezuela",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 230L,
                            CountryName = "Vietnam",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 231L,
                            CountryName = "Virgin Islands (British)",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 232L,
                            CountryName = "Virgin Islands (U.S.)",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 233L,
                            CountryName = "Wallis And Futuna Islands",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 234L,
                            CountryName = "Western Sahara",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 235L,
                            CountryName = "Yemen",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 236L,
                            CountryName = "Yugoslavia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 237L,
                            CountryName = "Zaire",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 238L,
                            CountryName = "Zambia",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 239L,
                            CountryName = "Zimbabwe",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 240L,
                            CountryName = "Guernsey",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 241L,
                            CountryName = "Malaga",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 242L,
                            CountryName = "Denmark",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        },
                        new
                        {
                            Id = 243L,
                            CountryName = "Jersey",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRemoved = false
                        });
                });

            modelBuilder.Entity("Sky.Domain.Entities.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<float?>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasMaxLength(10)
                        .HasColumnType("tinyint(10)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.Inventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InventoryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("InventoryName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Storekeeper")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("Sky.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientId = 1L,
                            Code = "001",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            FirstName = "admin",
                            IsRemoved = false,
                            LastName = "admin",
                            Password = "qKkxoCVZkDE+Mr9Yobrs5RGQBfngHc0SnKXDOn0m1LmarY/c",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
